name: local_regulations
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # workspaces
  sfera: 1.0.0

  # https://pub.dev/packages/collection
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0
