name: auth
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  # https://pub.dev/packages/meta
  meta: ^1.16.0
  # https://pub.dev/packages/sbb_oidc
  sbb_oidc: ^4.3.0
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/logging
  logging: ^1.3.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
