name: formation
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # workspaces
  http_x: 1.0.0

  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/drift
  drift: ^2.30.1
  # https://pub.dev/packages/drift_flutter
  drift_flutter: ^0.2.8
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/collection
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/mockito
  mockito: ^5.6.3
  # https://pub.dev/packages/build_runner
  build_runner: ^2.10.5
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.11.2
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.30.1
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0
