name: http_x
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # https://pub.dev/packages/http
  http: ^1.6.0
  # https://pub.dev/packages/http_interceptor
  http_interceptor: ^2.0.0
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/meta
  meta: ^1.17.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
