name: logger
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # workspaces
  http_x: 1.0.0

  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/ansicolor
  ansicolor: ^2.0.3
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/synchronized
  synchronized: ^3.4.0
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^12.3.0
  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^9.0.0
  # https://pub.dev/packages/clock
  clock: ^1.1.2
  # https://pub.dev/packages/path
  path: ^1.9.1
  # https://pub.dev/packages/get_it
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^2.10.5
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.11.2
  # https://pub.dev/packages/mockito
  mockito: ^5.6.3
  # https://pub.dev/packages/path_provider
  path_provider_platform_interface: any
  # https://pub.dev/packages/plugin_platform_interface
  plugin_platform_interface: any
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0

