name: app_links_x
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.8

resolution: workspace

dependencies:
  # https://pub.dev/packages/app_links
  app_links: ^7.0.0
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # https://pub.dev/packages/mockito
  mockito: ^5.6.3
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.11.2
  # https://pub.dev/packages/build_runner
  build_runner: ^2.11.1

