name: mqtt
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # workspaces
  connectivity_x: 1.0.0

  # https://pub.dev/packages/mqtt_client
  mqtt_client: ^10.11.6
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
