name: warnapp
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/sensors_plus
  sensors_plus: ^7.0.0
  # https://pub.dev/packages/geolocator
  geolocator: ^14.0.2
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^2.10.4
