name: connectivity_x
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # https://pub.dev/packages/logging
  connectivity_plus: ^7.0.0
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0
