spring:
  docker:
    compose:
      file: ./das_backend/compose.yaml
  config:
    import: optional:file:./das_backend/.env[.properties]
zis:
  clean-up:
    cron: '-'
  kafka:
    # disable kafka per default
    enabled: false
preload:
  kafka:
    # disable kafka per default
    enabled: false
  timetablePeriod:
    topic: nets-t.timetable
  timetableTrain:
    topic: fps.inte.sbbp.zug
  cleanUp:
    hours: 48
    cronExpression: "0 0 0 * * *"
