name: app
publish_to: 'none'
version: 0.34.0+76

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # workspace packages
  auth: 1.0.0
  logger: 1.0.0
  mqtt: 1.0.0
  sfera: 1.0.0
  http_x: 1.0.0
  warnapp: 1.0.0
  settings: 1.0.0
  connectivity_x: 1.0.0
  local_regulations: 1.0.0
  formation: 1.0.0

  # https://pub.dev/packages/audioplayers
  audioplayers: ^6.5.1
  # https://pub.dev/packages/android_id
  android_id: ^0.5.1
  # https://pub.dev/packages/auto_route
  auto_route: ^11.1.0
  # https://pub.dev/packages/battery_plus
  battery_plus: ^7.0.0
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/clock
  clock: ^1.1.2
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^12.3.0
  # https://pub.dev/packages/extra_hittest_area
  extra_hittest_area: ^1.0.0
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.2.3
  # https://pub.dev/packages/get_it
  get_it: ^9.2.0
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/meta
  meta: ^1.17.0
  # https://pub.dev/packages/provider
  provider: ^6.1.5+1
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

  # https://pub.dev/packages/sbb_design_system_mobile
  sbb_design_system_mobile: ^4.5.0
  # https://pub.dev/packages/volume_controller
  volume_controller: ^3.4.1
  # https://pub.dev/packages/wakelock_plus
  wakelock_plus: ^1.4.0
  # https://pub.dev/packages/screen_brightness/
  screen_brightness: ^2.1.7
  # https://pub.dev/packages/android_intent_plus
  android_intent_plus: ^6.0.0
  # https://pub.dev/packages/uuid
  uuid: ^4.5.2
  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^9.0.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.4
  # https://pub.dev/packages/webview_flutter
  webview_flutter: ^4.13.1
  # https://pub.dev/packages/skeletonizer
  skeletonizer: ^2.1.2
  # https://pub.dev/packages/appcheck
  appcheck: ^1.7.0
  # https://pub.dev/packages/dotted_border
  dotted_border: ^3.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^10.4.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.10.5
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.14.4
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/mockito
  mockito: ^5.6.3
  # https://pub.dev/packages/fake_async
  fake_async: ^1.3.3
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/others/
    - assets/fonts/
    - assets/sounds/
  fonts:
    - family: DasIcons
      fonts:
        - asset: assets/fonts/DasIcons.ttf
