name: preload
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # workspace
  settings: 1.0.0
  sfera: 1.0.0

  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/aws_common
  aws_common: ^0.7.12
  # https://pub.dev/packages/aws_signature_v4
  aws_signature_v4: ^0.6.10
  # https://pub.dev/packages/xml
  xml: ^6.6.1
  # https://pub.dev/packages/drift
  drift: ^2.30.1
  # https://pub.dev/packages/drift_flutter
  drift_flutter: ^0.2.8
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/archive
  archive: ^4.0.7
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0
  # https://pub.dev/packages/intl
  intl: ^0.20.2

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.10.5
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.30.1
